services:
  sparql-endpoint:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - KNOWLEDGE_ENGINE_URL=${KNOWLEDGE_ENGINE_URL}
      - KNOWLEDGE_BASE_ID_PREFIX=${KNOWLEDGE_BASE_ID_PREFIX}
      - TOKEN_ENABLED=${TOKEN_ENABLED}
      - TOKENS_FILE_PATH=${TOKENS_FILE_PATH}
      - SPARQL_ENDPOINT_NAME=${SPARQL_ENDPOINT_NAME}
      - ENABLE_REASONER=true
      - LOG_LEVEL=INFO
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/app
