services:
  sparql-endpoint:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - KNOWLEDGE_ENGINE_URL=${KNOWLEDGE_ENGINE_URL}
      - KNOWLEDGE_BASE_ID_PREFIX=${KNOWLEDGE_BASE_ID_PREFIX}
      - TOKEN_ENABLED=${TOKEN_ENABLED}
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
